@baseUrl = http://localhost:3000


# Users
# Create
POST {{baseUrl}}/users HTTP/1.1
Content-Type: application/json

{
  "name": "Bruno Angst",
  "email": "mbcangstb@gmail.com",
  "password": "1234"
}
###
{"name":"Bruno Angst","email":"mbcangst@gmail.com","password":"$2b$10$KQV.izhufs5vdS9Pfo92QOUGgp8xLovrhqq1buA/19xDOpKvuBQVy","id":"5f763187b222c987fe75c0ae"}
###

# Authenticate
POST {{baseUrl}}/users/authenticate HTTP/1.1
Content-Type: application/json

{
  "email": "mbcangstb@gmail.com",
  "password": "1234"
}

###
{"name":"Bruno Angst","email":"mbcangst@gmail.com","password":"$2b$10$KQV.izhufs5vdS9Pfo92QOUGgp8xLovrhqq1buA/19xDOpKvuBQVy","id":"5f763187b222c987fe75c0ae","token":"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiQnJ1bm8gQW5nc3QiLCJlbWFpbCI6Im1iY2FuZ3N0QGdtYWlsLmNvbSIsInBhc3N3b3JkIjoiJDJiJDEwJEtRVi5pemh1ZnM1dmRTOVBmbzkyUU9VR2dwOHhMb3ZyaHFxMWJ1QS8xOXhET3BLdnVCUVZ5IiwiaWQiOiI1Zjc2MzE4N2IyMjJjOTg3ZmU3NWMwYWUiLCJpYXQiOjE2MDE1ODE3MTgsImV4cCI6MTYwMTU4MTkxOH0._SlShSqY4rWbJO876LMhZYXtOitCIpjWGc2MfQCeSPQ"}
###

# Beach
# Create
POST {{baseUrl}}/beaches HTTP/1.1
Content-Type: application/json
Authorization: {{token}}

{
  "lat": -33.792726,
  "lng": 151.289824,
  "name": "Manly",
  "position": "E"
}
###

# Forecast
# Show
GET {{baseUrl}}/forecast HTTP/1.1

###

# Sessions
# Create
POST {{baseUrl}}/sessions HTTP/1.1
Content-Type: application/json

{
  "email": "abc@example.com",
  "password": "123"
}

###
# ForgotPassword
# Create
POST {{baseUrl}}/passwords HTTP/1.1
Content-Type: application/json

{
  "email": "abc@example.com",
  "redirect_url": "http://www.meusys.com/resetar_senha"
}

###
# Update
PUT {{baseUrl}}/passwords HTTP/1.1
Content-Type: application/json

{
  "token": "666a299529166c75eb85",
  "password": "123"
}

###
# Files
# Create
POST {{baseUrl}}/files HTTP/1.1
Content-Type: multipart/form-data; boundary=MyBoundary

--MyBoundary
Content-Disposition: form-data; name="file"; filename="caminhoCritico.png"
Content-Type: image/png

< ./../img/caminhoCritico.png
--MyBoundary--

###
# Show
GET {{baseUrl}}/files/1 HTTP/1.1.