@baseUrl = http://localhost:3000


# Users
# Create
POST {{baseUrl}}/users HTTP/1.1
Content-Type: application/json

{
  "name": "Bruno Angst",
  "email": "mbcangst2@gmail.com",
  "password": "1234"
}
###
{"name":"Bruno Angst","email":"mbcangst@gmail.com","password":"$2b$10$KQV.izhufs5vdS9Pfo92QOUGgp8xLovrhqq1buA/19xDOpKvuBQVy","id":"5f763187b222c987fe75c0ae"}
###

# Authenticate
POST {{baseUrl}}/users/authenticate HTTP/1.1
Content-Type: application/json

{
  "email": "mbcangst2@gmail.com",
  "password": "1234"
}

###

# Beach
# Create
POST {{baseUrl}}/beaches HTTP/1.1
Content-Type: application/json
x-access-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiQnJ1bm8gQW5nc3QiLCJlbWFpbCI6Im1iY2FuZ3N0MkBnbWFpbC5jb20iLCJwYXNzd29yZCI6IiQyYiQxMCRkQng5UzU0djlkdkFpTGJuTFE5L0Z1aUsxYXZBTkZSczFBTk5zeTNtUnc0MDdjYkc3cHVuUyIsImlkIjoiNWY3NmVjM2I1OTQ1NTAwYjE3NjEwNDFmIiwiaWF0IjoxNjAxNjI5MjQ4LCJleHAiOjE2MDE2Mjk0NDh9.vjexdJL6hZW0MU3QM_C89BSlRAdx1FrVXQr6fxtjZS8

{
  "lat": -33.792726,
  "lng": 151.289824,
  "name": "Manly",
  "position": "E"
}
###

# Forecast
# Show
GET {{baseUrl}}/forecast HTTP/1.1

###

# Sessions
# Create
POST {{baseUrl}}/sessions HTTP/1.1
Content-Type: application/json

{
  "email": "abc@example.com",
  "password": "123"
}

###
# ForgotPassword
# Create
POST {{baseUrl}}/passwords HTTP/1.1
Content-Type: application/json

{
  "email": "abc@example.com",
  "redirect_url": "http://www.meusys.com/resetar_senha"
}

###
# Update
PUT {{baseUrl}}/passwords HTTP/1.1
Content-Type: application/json

{
  "token": "666a299529166c75eb85",
  "password": "123"
}

###
# Files
# Create
POST {{baseUrl}}/files HTTP/1.1
Content-Type: multipart/form-data; boundary=MyBoundary

--MyBoundary
Content-Disposition: form-data; name="file"; filename="caminhoCritico.png"
Content-Type: image/png

< ./../img/caminhoCritico.png
--MyBoundary--

###
# Show
GET {{baseUrl}}/files/1 HTTP/1.1.